/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppointmentsRouteImport } from './routes/_authenticated/appointments'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedClinicsRouteImport } from './routes/_authenticated/clinics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedConsultationsIndexRouteImport } from './routes/_authenticated/consultations.index'
import { Route as AuthenticatedConsultationsNewRouteImport } from './routes/_authenticated/consultations.new'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients.$patientId'
import { Route as AuthenticatedPatientsNewRouteImport } from './routes/_authenticated/patients.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppointmentsRoute =
  AuthenticatedAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClinicsRoute = AuthenticatedClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultationsIndexRoute =
  AuthenticatedConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultationsNewRoute =
  AuthenticatedConsultationsNewRouteImport.update({
    id: '/consultations/new',
    path: '/consultations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsNewRoute =
  AuthenticatedPatientsNewRouteImport.update({
    id: '/patients/new',
    path: '/patients/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clinics': typeof AuthenticatedClinicsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AuthenticatedAppointmentsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/clinics': typeof AuthenticatedClinicsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/patients/new': typeof AuthenticatedPatientsNewRoute
  '/consultations': typeof AuthenticatedConsultationsIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/clinics': typeof AuthenticatedClinicsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRoute
  '/_authenticated/patients/new': typeof AuthenticatedPatientsNewRoute
  '/_authenticated/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/audit'
    | '/clinics'
    | '/dashboard'
    | '/schedule'
    | '/settings'
    | '/consultations/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/consultations/'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/appointments'
    | '/audit'
    | '/clinics'
    | '/dashboard'
    | '/schedule'
    | '/settings'
    | '/consultations/new'
    | '/patients/$patientId'
    | '/patients/new'
    | '/consultations'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/appointments'
    | '/_authenticated/audit'
    | '/_authenticated/clinics'
    | '/_authenticated/dashboard'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/consultations/new'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/patients/new'
    | '/_authenticated/consultations/'
    | '/_authenticated/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clinics': {
      id: '/_authenticated/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AuthenticatedClinicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations/': {
      id: '/_authenticated/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AuthenticatedConsultationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations/new': {
      id: '/_authenticated/consultations/new'
      path: '/consultations/new'
      fullPath: '/consultations/new'
      preLoaderRoute: typeof AuthenticatedConsultationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/new': {
      id: '/_authenticated/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AuthenticatedPatientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRoute: typeof AuthenticatedAppointmentsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedClinicsRoute: typeof AuthenticatedClinicsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedConsultationsNewRoute: typeof AuthenticatedConsultationsNewRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRoute
  AuthenticatedPatientsNewRoute: typeof AuthenticatedPatientsNewRoute
  AuthenticatedConsultationsIndexRoute: typeof AuthenticatedConsultationsIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRoute: AuthenticatedAppointmentsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedClinicsRoute: AuthenticatedClinicsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedConsultationsNewRoute: AuthenticatedConsultationsNewRoute,
  AuthenticatedPatientsPatientIdRoute: AuthenticatedPatientsPatientIdRoute,
  AuthenticatedPatientsNewRoute: AuthenticatedPatientsNewRoute,
  AuthenticatedConsultationsIndexRoute: AuthenticatedConsultationsIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
